add_newline = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

#[character]
#success_symbol = "[âœ](bold green)"
#error_symbol = "[âœ—](bold red)"

[kubernetes]
symbol = "âˆ "
format = "[$symbol$cluster]($style) "
style = "bright-yellow"
disabled = false

